// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '...',
    appId: '1:5189700141:web:64995b9b480cab5add46a4',
    messagingSenderId: '5189700141',
    projectId: 'farpooper-61063',
    authDomain: 'farpooper-61063.firebaseapp.com',
    storageBucket: 'farpooper-61063.firebasestorage.app',
    measurementId: 'G-D2GM27J9W0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '...',
    appId: '1:5189700141:ios:9760d406267b9f51dd46a4',
    messagingSenderId: '5189700141',
    projectId: 'farpooper-61063',
    storageBucket: 'farpooper-61063.firebasestorage.app',
    iosClientId: '5189700141-imobp9ob0ql846a0mvg7b7u3l2isvqhd.apps.googleusercontent.com',
    iosBundleId: 'lluis.itarte.sahun.farpooperFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '...',
    appId: '1:5189700141:web:5ac54f3395be95c8dd46a4',
    messagingSenderId: '5189700141',
    projectId: 'farpooper-61063',
    authDomain: 'farpooper-61063.firebaseapp.com',
    storageBucket: 'farpooper-61063.firebasestorage.app',
    measurementId: 'G-12JJGNHX0D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '...',
    appId: '1:5189700141:ios:9760d406267b9f51dd46a4',
    messagingSenderId: '5189700141',
    projectId: 'farpooper-61063',
    storageBucket: 'farpooper-61063.firebasestorage.app',
    iosClientId: '5189700141-imobp9ob0ql846a0mvg7b7u3l2isvqhd.apps.googleusercontent.com',
    iosBundleId: 'lluis.itarte.sahun.farpooperFrontend',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '...',
    appId: '1:5189700141:android:771f1cdc5c07a111dd46a4',
    messagingSenderId: '5189700141',
    projectId: 'farpooper-61063',
    storageBucket: 'farpooper-61063.firebasestorage.app',
  );

}